version: '3.7'

services:

  app:
    build:
      context: .
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    command: sh -c "python ./app/manage.py runserver 0.0.0.0:8000"
    container_name: django-app
    environment: 
      - DEBUG=1
    restart: on-failure